import { CodeMap } from './code-map';
import { TwoDimension, ThreeDimension } from './dimension';
import { SpecError } from './error';
import { DoorValue, EnvMonitorValue, PowerGridValue, UPSValue, RFIDTagValue, CallValue, VideoAnalyseValue, VideoAnalyseType, Face, CarPlate, DeviceControlParam, InterfaceInitParam, InterfaceDescripter, DeviceEventData } from './device-interface';
import { Message } from './message';
import { RestQuery, RestResponse } from './rest';
import { Service, ServiceFinder, ServiceRegister } from './service';
import { Option } from './option';
declare const _default: {
    CodeMap: typeof CodeMap;
    SpecError: typeof SpecError;
    TwoDimension: typeof TwoDimension;
    ThreeDimension: typeof ThreeDimension;
    Config: {
        envDevelopment: string;
        envProducton: string;
        defaultConfigPath: string;
        serviceHubPort: number;
    };
    ResourceCode: CodeMap[];
    InterfaceCategory: CodeMap[];
    InterfaceInitParamOption: Option.IInterfaceInitParamOption;
    InterfaceInitParam: typeof InterfaceInitParam;
    Message: typeof Message;
    MessageTopic: {
        deviceEvent: CodeMap;
        deviceStatus: CodeMap;
        deviceFault: CodeMap;
        deviceControl: CodeMap;
        custom: CodeMap;
        others: CodeMap;
    };
    MessageType: {
        unknown: CodeMap;
        deviceEvent: CodeMap;
        deviceStatus: CodeMap;
        deviceFault: CodeMap;
        deviceControl: CodeMap;
        custom: CodeMap;
        others: CodeMap;
    };
    DeviceAlarmCode: CodeMap[];
    DeviceEventCode: CodeMap[];
    DeviceStatusCode: CodeMap[];
    DeviceFaultCode: CodeMap[];
    DeviceControlCode: {
        stopInterface: number;
        awayArm: number;
        stayArm: number;
        disArm: number;
        connectRelay: number;
        disconnectRelay: number;
        byPass: number;
        cancelByPass: number;
        query: number;
        callSlave: number;
        listenSlave: number;
        hangupSlave: number;
        startBroadcast: number;
        stopBroadcast: number;
        setContent: number;
        sesumeContent: number;
        switchDecoderChannel: number;
        switchMatrixChannel: number;
        matrixPTZ: number;
        matrixPreset: number;
        tvWallLayout: number;
        openDoor: number;
        closeDoor: number;
        resetArm: number;
        stayClose: number;
        resumeStatus: number;
        voiceBroadcast: number;
        openWindow: number;
        closeWindow: number;
        stopProcedure: number;
        acOn: number;
        acOff: number;
        acMode: number;
        acTemperature: number;
        cmd: number;
    };
    DoorValue: typeof DoorValue;
    EnvMonitorValue: typeof EnvMonitorValue;
    PowerGridValue: typeof PowerGridValue;
    UPSValue: typeof UPSValue;
    RFIDTagValue: typeof RFIDTagValue;
    CallValue: typeof CallValue;
    VideoAnalyseValue: typeof VideoAnalyseValue;
    VideoAnalyseType: typeof VideoAnalyseType;
    Face: typeof Face;
    CarPlate: typeof CarPlate;
    RestQuery: typeof RestQuery;
    RestResponse: typeof RestResponse;
    RestQueryOption: Option.IRestQueryOption;
    RestResponseOption: Option.IRestResponseOption;
    DeviceControlParam: typeof DeviceControlParam;
    InterfaceDescripter: typeof InterfaceDescripter;
    DeviceEventType: {
        unknown: number;
        status: number;
        normal: number;
        alarm: number;
        fault: number;
    };
    DeviceEventData: typeof DeviceEventData;
    Service: typeof Service;
    ServiceFinder: typeof ServiceFinder;
    ServiceRegister: typeof ServiceRegister;
    ServiceType: {
        unknown: CodeMap;
        identityService: CodeMap;
        fileHub: CodeMap;
        deviceService: CodeMap;
        cloudProxyService: CodeMap;
        monitorService: CodeMap;
        messageHub: CodeMap;
        eventService: CodeMap;
        logService: CodeMap;
        timeSerialService: CodeMap;
    };
};
export default _default;
