'use strict';

module.exports.unknown = -1;
module.exports.areaAlarm = 0;
module.exports.motionDetec = 1;
module.exports.videoLost = 2;
module.exports.videoShelter = 3;
module.exports.soundCheck = 4;
module.exports.diskFull = 5;
module.exports.diskFault = 6;
module.exports.soundLost = 7;
module.exports.deviceAbnormal = 8;
module.exports.areaIntrusion = 9;
module.exports.linitHeight = 10;
module.exports.wander = 11;
module.exports.raiseup = 12;
module.exports.targetLost = 13;
module.exports.abnormalBehavior = 14;
module.exports.objectLeft = 15;
module.exports.stay = 16;
module.exports.timeout = 17;
module.exports.invalidOperation = 18;
module.exports.threatOperation = 19;
module.exports.remove = 20;
module.exports.offline = 21;
module.exports.powerUnstable = 22;
module.exports.disturb = 23;
module.exports.deviceLost = 24;
module.exports.bypass = 25;
module.exports.inactive = 26;
module.exports.recordStop = 27;
module.exports.powerAbnormal = 28;
module.exports.videoQuality = 29;
module.exports.dutyCheck = 30;
module.exports.fierceMotion = 31;
module.exports.deviceFault = 32;
module.exports.audioLost = 33;
module.exports.fanFault = 34;
module.exports.temperatureAlarm = 35;
module.exports.humidityAlarm = 36;
module.exports.doorPointAlarm = 37;
module.exports.forceOperation = 38;

Object.freeze(module.exports);

