'use strict';

module.exports.Unknown = 1;
module.exports.AreaAlarm = 0;
module.exports.MotionDetec = 1;
module.exports.VideoLost = 2;
module.exports.VideoShelter = 3;
module.exports.SoundCheck = 4;
module.exports.DiskFull = 5;
module.exports.DiskFault = 6;
module.exports.SoundLost = 7;
module.exports.DeviceAbnormal = 8;
module.exports.AreaIntrusion = 9;
module.exports.LinitHeight = 10;
module.exports.Wander = 11;
module.exports.Raiseup = 12;
module.exports.TargetLost = 13;
module.exports.AbnormalBehavior = 14;
module.exports.ObjectLeft = 15;
module.exports.stay = 16;
module.exports.Timeout = 17;
module.exports.InvalidOperation = 18;
module.exports.ThreatOperation = 19;
module.exports.Remove = 20;
module.exports.Offline = 21;
module.exports.PowerUnstable = 22;
module.exports.Disturb = 23;
module.exports.DeviceLost = 24;
module.exports.Bypass = 25;
module.exports.Inactive = 26;
module.exports.RecordStop = 27;
module.exports.PowerAbnormal = 28;
module.exports.VideoQuality = 29;
module.exports.DutyCheck = 30;
module.exports.FierceMotion = 31;
module.exports.DeviceFault = 32;
module.exports.AudioLost = 33;
module.exports.FanFault = 34;
module.exports.TemperatureAlarm = 35;
module.exports.HumidityAlarm = 36;
module.exports.DoorPointAlarm = 37;
module.exports.ForceOperation = 38;

Object.freeze(exports);

