import { CodeMap } from './code-map';

export const DeviceAlarmCode: Array<CodeMap> = [
    CodeMap.from('-1', '未知类型'),
    CodeMap.from('0', '防区报警'),
    CodeMap.from('1', '区域入侵'),
    CodeMap.from('2', '限高'),
    CodeMap.from('3', '徘徊'),
    CodeMap.from('4', '起身'),
    CodeMap.from('5', '目标丢失'),
    CodeMap.from('6', '异常行为'),
    CodeMap.from('7', '物品遗留'),
    CodeMap.from('8', '停留'),
    CodeMap.from('9', '非法操作'),
    CodeMap.from('10', '胁迫操作'),
    CodeMap.from('11', '脱岗'),
    CodeMap.from('12', '剧烈运动'),
    CodeMap.from('13', '温度报警'),
    CodeMap.from('14', '强行闯入'),
    CodeMap.from('15', '分贝报警'),
    CodeMap.from('16', '人脸布防报警'),
    CodeMap.from('17', '腕带断开报警'),
    CodeMap.from('18', '心率异常报警'),
    CodeMap.from('19', '标签按钮报警'),
    CodeMap.from('20', '烟雾报警'),
    CodeMap.from('21', '火警'),
    CodeMap.from('22', '人员聚集报警'),
    CodeMap.from('23', '值班睡觉'),
    CodeMap.from('24', '打架'),
    CodeMap.from('25', '无人值守'),
    CodeMap.from('26', '高压断网报警'),
    CodeMap.from('27', '高压触网报警'),
    CodeMap.from('28', '高压短路报警')
];